server:
  defaultPort: 3001
  env: prod
  inferencePath: http://172.31.208.92:8033
  source: 5ZiaO3BlNIL9uUsDWG5s

mysql:
  dbMysqlAddress: [ psyckey-main-database.cluster-clonlmtipukq.us-east-2.rds.amazonaws.com ]
  dbMysqlUserName: PsyckeyDBAdmin
  dbMysqlPassword: PK6&db*A0-3B%s#52
  dbMysqlDatabaseName: chara
  dbCharset: utf8mb4
  dbMaxOpenConns: 100
  dbMaxIdleConns: 20
  dbMaxLifeTime: 3600
  dbMaxIdleTime: 600
  logLevel: 2 #1=slient 2=error 3=warn 4=info
  slowThreshold: 200
  # 只读库配置
  readDbMysqlAddress: [ psyckey-main-database.cluster-ro-clonlmtipukq.us-east-2.rds.amazonaws.com ]
  readDbMysqlUserName: PsyckeyDBAdmin
  readDbMysqlPassword: PK6&db*A0-3B%s#52
  readDbMysqlDatabaseName: chara
  readDbCharset: utf8mb4
  readDbMaxOpenConns: 100
  readDbMaxIdleConns: 20
  readDbMaxLifeTime: 3600
  readDbMaxIdleTime: 600

redis:
  dbAddress: [ 172.31.22.144:6379 ]
  dbIdleTimeout: 120
  dbUserName:
  dbPassWord:
  dbPoolSize: 100
  dbIndex: 1
  enableCluster: false

logSetting:
  logLevel: 2
  logName: llm-api
  compressSize: 100
  rotationNum: 10

prometheus:
  enable: true
